blank_issues_enabled: true
contact_links: []
issue_templates:
  - name: ğŸ Bug Report
    description: Report an issue or unexpected behavior
    file: defect_report.yml
  - name: âœ¨ Feature Request
    description: Suggest a new feature or improvement
    file: feature_request.yml
  - name: ğŸ“š User Story
    description: Describe a user story to help guide development
    file: user_story.yml
